# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script into the container
COPY app.py .

# Copy the backend and frontend directories into the container
COPY backend/ backend/
COPY frontend/ frontend/
COPY artifacts/ artifacts/

# Set the command to run the Python script
CMD ["python", "app.py"]